/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EventsRouteImport } from './routes/events'
import { Route as GradesRouteImport } from './routes/grades'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LecturesRouteImport } from './routes/lectures'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as SubjectKeyRouteImport } from './routes/subject.$key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const GradesRoute = GradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LecturesRoute = LecturesRouteImport.update({
  id: '/lectures',
  path: '/lectures',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectKeyRoute = SubjectKeyRouteImport.update({
  id: '/subject/$key',
  path: '/subject/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/grades': typeof GradesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lectures': typeof LecturesRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/resources': typeof ResourcesRoute
  '/tests': typeof TestsRoute
  '/subject/$key': typeof SubjectKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/grades': typeof GradesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lectures': typeof LecturesRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/resources': typeof ResourcesRoute
  '/tests': typeof TestsRoute
  '/subject/$key': typeof SubjectKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assignments': typeof AssignmentsRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/grades': typeof GradesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/lectures': typeof LecturesRoute
  '/messages': typeof MessagesRoute
  '/profile': typeof ProfileRoute
  '/quiz': typeof QuizRoute
  '/resources': typeof ResourcesRoute
  '/tests': typeof TestsRoute
  '/subject/$key': typeof SubjectKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assignments'
    | '/auth'
    | '/events'
    | '/grades'
    | '/leaderboard'
    | '/lectures'
    | '/messages'
    | '/profile'
    | '/quiz'
    | '/resources'
    | '/tests'
    | '/subject/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assignments'
    | '/auth'
    | '/events'
    | '/grades'
    | '/leaderboard'
    | '/lectures'
    | '/messages'
    | '/profile'
    | '/quiz'
    | '/resources'
    | '/tests'
    | '/subject/$key'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assignments'
    | '/auth'
    | '/events'
    | '/grades'
    | '/leaderboard'
    | '/lectures'
    | '/messages'
    | '/profile'
    | '/quiz'
    | '/resources'
    | '/tests'
    | '/subject/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssignmentsRoute: typeof AssignmentsRoute
  AuthRoute: typeof AuthRoute
  EventsRoute: typeof EventsRoute
  GradesRoute: typeof GradesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LecturesRoute: typeof LecturesRoute
  MessagesRoute: typeof MessagesRoute
  ProfileRoute: typeof ProfileRoute
  QuizRoute: typeof QuizRoute
  ResourcesRoute: typeof ResourcesRoute
  TestsRoute: typeof TestsRoute
  SubjectKeyRoute: typeof SubjectKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grades': {
      id: '/grades'
      path: '/grades'
      fullPath: '/grades'
      preLoaderRoute: typeof GradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lectures': {
      id: '/lectures'
      path: '/lectures'
      fullPath: '/lectures'
      preLoaderRoute: typeof LecturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subject/$key': {
      id: '/subject/$key'
      path: '/subject/$key'
      fullPath: '/subject/$key'
      preLoaderRoute: typeof SubjectKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssignmentsRoute: AssignmentsRoute,
  AuthRoute: AuthRoute,
  EventsRoute: EventsRoute,
  GradesRoute: GradesRoute,
  LeaderboardRoute: LeaderboardRoute,
  LecturesRoute: LecturesRoute,
  MessagesRoute: MessagesRoute,
  ProfileRoute: ProfileRoute,
  QuizRoute: QuizRoute,
  ResourcesRoute: ResourcesRoute,
  TestsRoute: TestsRoute,
  SubjectKeyRoute: SubjectKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
